<?php

namespace Test;

use App\AirQualityApiService;
use PHPUnit\Framework\TestCase;

class AirQualityApiServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
